In [1]:
# Numpy - Numerical Python
# Mathematical Computation Library
# Mostly used for Array - 1D, 2D, 3D... ND
# Base library for Pandas, OpenCV
# Base Library for frameworks of deep learrning like Tensorflow, PyTorch

In [2]:
import numpy as np

## Ways to create array

In [3]:
# 1. Using np.array([])
x = np.array([4,5,6,7,9,1,32,5,8,8,24])

In [4]:
x

array([ 4,  5,  6,  7,  9,  1, 32,  5,  8,  8, 24])

In [5]:
np.array([5,4,5,6,5.7])

array([5. , 4. , 5. , 6. , 5.7])

In [6]:
np.array([5,4,5,6,5.7,True])

array([5. , 4. , 5. , 6. , 5.7, 1. ])

In [7]:
np.array([5,4,5,6,5.7,True,"hi"])

array(['5', '4', '5', '6', '5.7', 'True', 'hi'], dtype='<U32')

In [8]:
# 2. Using np.arange
x = np.arange(1,21)

In [9]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [10]:
x = np.arange(1,21,2)

In [11]:
x

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [12]:
# 3. Using np.linspace -> linear space
np.linspace(1,10)
# it creates by default array of 50 elements within given range with equal interval

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [13]:
np.linspace(1,10,8)

array([ 1.        ,  2.28571429,  3.57142857,  4.85714286,  6.14285714,
        7.42857143,  8.71428571, 10.        ])

In [14]:
np.linspace(1,10,8,retstep=True)
# it will create array with 8 elements within range 0f 1 to 10

(array([ 1.        ,  2.28571429,  3.57142857,  4.85714286,  6.14285714,
         7.42857143,  8.71428571, 10.        ]),
 1.2857142857142858)

In [17]:
# 4. Using np.random
np.random.random()
# it will create random number b/w 0 to 1

0.4816723004938901

In [18]:
np.random.random(5)

array([0.94339286, 0.18408837, 0.17227053, 0.74697   , 0.93710813])

In [20]:
np.random.random(size=(5,4))
# it will create a matrix of 5x4

array([[0.67184092, 0.64025156, 0.24850991, 0.21912276],
       [0.83349351, 0.45427219, 0.30248132, 0.8634332 ],
       [0.74098936, 0.18633114, 0.09116865, 0.85864498],
       [0.23875653, 0.96522876, 0.52010461, 0.70997317],
       [0.55113031, 0.82855672, 0.48848095, 0.78638996]])

In [21]:
np.random.randn()

-0.48657778159788034

In [22]:
np.random.randn(5)

array([-0.79541454,  0.43352393, -1.33993245,  2.03305922,  0.75729476])

In [23]:
np.random.randn(5,4)

array([[-1.40039907, -0.76508098,  1.17713888, -0.48951483],
       [ 0.87193229, -1.55194876, -1.45126316,  0.7861946 ],
       [-0.81460392, -1.00820749, -1.71698622,  0.57136442],
       [-0.52129007, -0.51980921, -0.00986995, -1.13554464],
       [ 0.32598734,  0.43489017,  0.60139438, -0.41980431]])

In [24]:
np.random.randint(1,50)

33

In [25]:
np.random.randint(1,50,8)

array([13, 34, 33, 33, 27, 46, 28,  3])

In [26]:
np.random.randint(1,50,(5,4))

array([[17, 16, 37,  3],
       [19, 42, 11, 37],
       [44, 30, 33, 38],
       [30, 47, 30, 29],
       [35,  7, 27,  8]])

In [27]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [28]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [30]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
x = np.random.randint(1,50,(5,4))

In [32]:
x

array([[30, 43, 45,  4],
       [17, 41, 44, 38],
       [39, 49, 30, 32],
       [16, 48, 27,  4],
       [ 8, 47, 48, 40]])

In [34]:
np.zeros_like(x)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

## Multi-Dimensional Array 

In [35]:
# 1D Array
# np.array([4,56,7,8,4,3])

# 2D Array
np.array([[1,2,3], [5,6,4], [3,8,6], [4,3,2]])

array([[1, 2, 3],
       [5, 6, 4],
       [3, 8, 6],
       [4, 3, 2]])

In [36]:
# 3D Array
np.array([[[4,5,6], [2,3,1]], [[4,5,6], [2,3,1]], [[4,5,6], [2,3,1]]])

array([[[4, 5, 6],
        [2, 3, 1]],

       [[4, 5, 6],
        [2, 3, 1]],

       [[4, 5, 6],
        [2, 3, 1]]])

## Indexing and Slicing 

In [37]:
# Indexing and Slicing 1D Array
x = np.random.randint(4,25,15)

In [38]:
x

array([15, 14, 22, 19, 14,  5,  5, 19, 12,  9, 19, 15, 10,  9, 20])

In [39]:
x[0]

15

In [40]:
x[-1]

20

In [41]:
x[:5]

array([15, 14, 22, 19, 14])

In [42]:
x[5:10]

array([ 5,  5, 19, 12,  9])

In [43]:
x[::-1]

array([20,  9, 10, 15, 19,  9, 12, 19,  5,  5, 14, 19, 22, 14, 15])

In [44]:
# Indexing and Slicing 2D Array
x = np.random.randint(4,25,(5,6))

In [45]:
x

array([[17, 18, 13,  6, 21, 20],
       [22, 12,  5,  6, 23, 13],
       [ 9, 23, 19, 16, 17, 15],
       [14, 21, 17, 24,  6,  4],
       [ 4, 18,  8, 20, 16,  9]])

In [46]:
# return 1st row
x[0]

array([17, 18, 13,  6, 21, 20])

In [47]:
# return 2nd row
x[1]

array([22, 12,  5,  6, 23, 13])

In [48]:
# will return 1st, 2nd and 3rd row
x[0:3]

array([[17, 18, 13,  6, 21, 20],
       [22, 12,  5,  6, 23, 13],
       [ 9, 23, 19, 16, 17, 15]])

In [50]:
x[0][0]

17

In [51]:
# will return all the rows but 1st column only
x[:,0]

array([17, 22,  9, 14,  4])

In [52]:
# will return all the rows but 1st column only in 2 Dimension
x[:,0:1]

array([[17],
       [22],
       [ 9],
       [14],
       [ 4]])

In [53]:
# Slicing columns from 0 to 2
x[:,0:2]

array([[17, 18],
       [22, 12],
       [ 9, 23],
       [14, 21],
       [ 4, 18]])

In [54]:
x[:,0:3]

array([[17, 18, 13],
       [22, 12,  5],
       [ 9, 23, 19],
       [14, 21, 17],
       [ 4, 18,  8]])

In [55]:
x[0:3, 0:3]

array([[17, 18, 13],
       [22, 12,  5],
       [ 9, 23, 19]])

## Methods of Numpy 

In [56]:
x = np.random.randint(4,20,24)

In [57]:
x

array([18, 12,  4, 13, 18, 15, 18,  5,  7, 16,  8,  8,  7,  8,  7,  9, 16,
        9, 13, 13, 13,  5,  4,  9])

In [58]:
x.shape

(24,)

In [59]:
x.sum()

255

In [60]:
np.sum(x)

255

In [61]:
np.mean(x)

10.625

In [62]:
np.median(x)

9.0

In [63]:
np.std(x)

4.488991163576363

In [64]:
np.var(x)

20.151041666666668

In [65]:
np.max(x)

18

In [66]:
np.min(x)

4

In [67]:
np.sort(x)

array([ 4,  4,  5,  5,  7,  7,  7,  8,  8,  8,  9,  9,  9, 12, 13, 13, 13,
       13, 15, 16, 16, 18, 18, 18])

In [68]:
# Index of max
np.argmax(x)

0

In [69]:
# Index of min
np.argmin(x)

2

In [70]:
y = np.reshape(x, (4,6))

In [71]:
y

array([[18, 12,  4, 13, 18, 15],
       [18,  5,  7, 16,  8,  8],
       [ 7,  8,  7,  9, 16,  9],
       [13, 13, 13,  5,  4,  9]])

In [72]:
np.sum(y)

255

In [73]:
# sum of each row
np.sum(y, axis=1)

array([80, 62, 56, 57])

In [74]:
# sum of each col
np.sum(y, axis=0)

array([56, 38, 31, 43, 46, 41])

In [76]:
np.mean(y, axis=0)

array([14.  ,  9.5 ,  7.75, 10.75, 11.5 , 10.25])

In [77]:
np.mean(y, axis=1)

array([13.33333333, 10.33333333,  9.33333333,  9.5       ])

In [78]:
y

array([[18, 12,  4, 13, 18, 15],
       [18,  5,  7, 16,  8,  8],
       [ 7,  8,  7,  9, 16,  9],
       [13, 13, 13,  5,  4,  9]])

In [85]:
# adding a column in array
y1 = np.array([[1],[2],[3],[4]])
np.hstack((y, y1))

array([[18, 12,  4, 13, 18, 15,  1],
       [18,  5,  7, 16,  8,  8,  2],
       [ 7,  8,  7,  9, 16,  9,  3],
       [13, 13, 13,  5,  4,  9,  4]])

In [86]:
y2 = np.array([[1,2,3,4,5,6]])
np.vstack((y,y2))

array([[18, 12,  4, 13, 18, 15],
       [18,  5,  7, 16,  8,  8],
       [ 7,  8,  7,  9, 16,  9],
       [13, 13, 13,  5,  4,  9],
       [ 1,  2,  3,  4,  5,  6]])

In [87]:
np.c_[y, y1]

array([[18, 12,  4, 13, 18, 15,  1],
       [18,  5,  7, 16,  8,  8,  2],
       [ 7,  8,  7,  9, 16,  9,  3],
       [13, 13, 13,  5,  4,  9,  4]])

In [88]:
np.r_[y, y2]

array([[18, 12,  4, 13, 18, 15],
       [18,  5,  7, 16,  8,  8],
       [ 7,  8,  7,  9, 16,  9],
       [13, 13, 13,  5,  4,  9],
       [ 1,  2,  3,  4,  5,  6]])

In [90]:
y

array([[18, 12,  4, 13, 18, 15],
       [18,  5,  7, 16,  8,  8],
       [ 7,  8,  7,  9, 16,  9],
       [13, 13, 13,  5,  4,  9]])

In [89]:
np.where(y > 10)

(array([0, 0, 0, 0, 0, 1, 1, 2, 3, 3, 3], dtype=int64),
 array([0, 1, 3, 4, 5, 0, 3, 4, 0, 1, 2], dtype=int64))

In [93]:
np.where(y > 14)

(array([0, 0, 0, 1, 1, 2], dtype=int64),
 array([0, 4, 5, 0, 3, 4], dtype=int64))

In [95]:
np.where(y > 14, 0, y)

array([[ 0, 12,  4, 13,  0,  0],
       [ 0,  5,  7,  0,  8,  8],
       [ 7,  8,  7,  9,  0,  9],
       [13, 13, 13,  5,  4,  9]])

In [96]:
np.where(y > 14, 0, 1)

array([[0, 1, 1, 1, 0, 0],
       [0, 1, 1, 0, 1, 1],
       [1, 1, 1, 1, 0, 1],
       [1, 1, 1, 1, 1, 1]])

In [97]:
# no specific range
np.cov(y)

array([[ 27.06666667,  11.46666667,   8.66666667,  -9.2       ],
       [ 11.46666667,  28.26666667,  -3.93333333,  -3.        ],
       [  8.66666667,  -3.93333333,  11.46666667, -11.2       ],
       [ -9.2       ,  -3.        , -11.2       ,  17.5       ]])

In [99]:
# range is from -1 to +1
np.corrcoef(y)

array([[ 1.        ,  0.41455533,  0.4919445 , -0.42271866],
       [ 0.41455533,  1.        , -0.21847657, -0.1348854 ],
       [ 0.4919445 , -0.21847657,  1.        , -0.79064295],
       [-0.42271866, -0.1348854 , -0.79064295,  1.        ]])

## Broadcasting 

In [101]:
y + 1

array([[19, 13,  5, 14, 19, 16],
       [19,  6,  8, 17,  9,  9],
       [ 8,  9,  8, 10, 17, 10],
       [14, 14, 14,  6,  5, 10]])

In [102]:
y - 5

array([[13,  7, -1,  8, 13, 10],
       [13,  0,  2, 11,  3,  3],
       [ 2,  3,  2,  4, 11,  4],
       [ 8,  8,  8,  0, -1,  4]])

In [103]:
x = np.random.randint(1,10,(3,4))
y = np.random.randint(10,20,(3,4))

In [104]:
x

array([[2, 6, 4, 8],
       [4, 1, 4, 6],
       [9, 9, 6, 3]])

In [105]:
y

array([[17, 13, 10, 17],
       [10, 13, 13, 13],
       [19, 10, 11, 12]])

In [106]:
x + y

array([[19, 19, 14, 25],
       [14, 14, 17, 19],
       [28, 19, 17, 15]])

In [107]:
x * y

array([[ 34,  78,  40, 136],
       [ 40,  13,  52,  78],
       [171,  90,  66,  36]])